# Generated by Django 3.1.2 on 2020-10-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, choices=[('Engineering', 'Engineering'), ('Studies of Management', 'Studies of Management'), ('Journalism And Mass Communication', 'Journalism And Mass Communication'), ('Arts And Humanities', 'Arts And Humanities'), ('Hotel & Hospitality Management', 'Hotel & Hospitality Management'), ('School Of Legal Studies', 'School Of Legal Studies'), ('(PhD) Doctor Of Philosophy', '(PhD) Doctor Of Philosophy')], max_length=35),
        ),
    ]
