# Generated by Django 3.1.2 on 2020-10-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bankdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='BankDetail',
        ),
    ]
