# Generated by Django 3.1.2 on 2020-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201009_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='acc_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank IFSC Code'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name="Account Holder's Name"),
        ),
    ]
