# Generated by Django 3.1.2 on 2020-10-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_paid'),
        ('account', '0005_auto_20201009_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_project', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
