# Generated by Django 2.2.6 on 2020-09-10 01:10

import blog.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(default='', max_length=200, validators=[blog.validators.validate_geeks2])),
                ('designation', models.CharField(default='', max_length=200, validators=[blog.validators.validate_geeks2])),
                ('description', models.TextField(default='', max_length=1000, validators=[blog.validators.validate_geeks2])),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='College or educational institute name')),
                ('image1', models.ImageField(default='', upload_to='student_docs', verbose_name='Front Side Of ID Card')),
                ('image2', models.ImageField(default='', upload_to='student_docs', verbose_name='Back Side Of ID Card')),
                ('check', models.BooleanField(blank=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SampleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('playstore_link', models.URLField(blank=True)),
                ('other_link', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, default='', max_length=200, validators=[blog.validators.validate_geeks2], verbose_name='Project Title')),
                ('project_description', models.TextField(blank=True, default='', max_length=500, validators=[blog.validators.validate_geeks2])),
                ('project_link', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievments', models.CharField(default='', max_length=1000, validators=[blog.validators.validate_geeks2])),
                ('details', models.TextField(default='', help_text='Describe Your Achievments in a fun and brief way.', max_length=1000, validators=[blog.validators.validate_geeks2])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=200, verbose_name='What is your level in this skill?')),
                ('skillsets', taggit.managers.TaggableManager(help_text='NOTE: Create your custom skills tag, if not in the list.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Skillsets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('SE', 'Secondary Education'), ('SSE', 'Senior Secondary Education'), ('U', 'Undergraduation'), ('PG', 'Post Graduation'), ('Dip', 'Diploma'), ('Doc', 'Ph.D'), ('Self', 'Self Taught/Professional Certifications')], max_length=4)),
                ('institution_name', models.CharField(default='', max_length=100)),
                ('course', models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Animation & Multimedia', 'Animation & Multimedia'), ('Health Science', 'Health Science'), ('Agricultural Science', 'Agricultural Science'), ('Arts & Humanities', 'Arts & Humanities')], max_length=25)),
                ('score', models.FloatField()),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
