# Generated by Django 3.1.2 on 2020-10-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='level',
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True, help_text='Only GitHub Link is Accepted'),
        ),
    ]
