# Generated by Django 3.1.2 on 2020-10-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201007_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Animation & Multimedia', 'Animation & Multimedia'), ('Health Science', 'Health Science'), ('Agricultural Science', 'Agricultural Science'), ('Arts & Humanities', 'Arts & Humanities'), ('Hospitality', 'Hospitality'), ('Other', 'Other')], max_length=25),
        ),
    ]
