# Generated by Django 3.1.2 on 2020-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201008_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
