# Generated by Django 2.2.6 on 2020-09-10 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', unique=True)),
                ('pitch', models.TextField(max_length=1000, verbose_name='Project Pitch')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='blog.Post')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(default='', max_length=2000)),
                ('order_id', models.CharField(default='No Payment', max_length=1000)),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('doer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doer_user', to=settings.AUTH_USER_MODEL)),
                ('ongoing_project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_project', to='blog.Post')),
            ],
        ),
    ]
