# Generated by Django 2.2.6 on 2020-09-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend_request_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='request_submit',
        ),
    ]
