# Generated by Django 2.2.6 on 2020-09-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_friend_request_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='submission_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
