# Generated by Django 2.2.6 on 2020-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friend_submission_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='submission_count',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
