# Generated by Django 2.2.6 on 2020-09-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20200921_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='submission_count',
        ),
    ]
