# Generated by Django 2.2.6 on 2020-09-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20200926_0406'),
        ('friends', '0006_remove_friend_submission_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='invoice_docs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_project', to='blog.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
