# Generated by Django 3.1.2 on 2020-10-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='paid_by_peerwork',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
