# Generated by Django 2.2.6 on 2020-09-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='request_submit',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
