# Generated by Django 2.2.6 on 2020-09-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_request_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='request_submit',
        ),
    ]
