# Generated by Django 2.2.6 on 2020-09-19 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_post_request_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_submit', models.BooleanField(blank=True, default=False)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('on_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_project', to='blog.Post')),
                ('project_doer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_doer_user', to=settings.AUTH_USER_MODEL)),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
