# Generated by Django 2.2.6 on 2020-09-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_submitform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='on_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_project', to='blog.Post'),
        ),
    ]
