# Generated by Django 2.2.6 on 2020-09-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200919_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='blog.Post')),
            ],
        ),
    ]
