# Generated by Django 2.2.6 on 2020-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200920_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='granted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
