# Generated by Django 2.2.6 on 2020-09-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200921_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawproject',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='blog.Post'),
        ),
    ]
