# Generated by Django 2.2.6 on 2020-09-21 14:38

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200921_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Max Length : 50 chars', max_length=50, unique=True, validators=[blog.validators.validate_geeks2], verbose_name='What is your project about?'),
        ),
    ]
