# Generated by Django 3.1.2 on 2020-10-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200926_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='paid',
        ),
    ]
